# Generated by Django 3.1.13 on 2021-11-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineeraddon',
            name='skills',
            field=models.ManyToManyField(related_name='engineers', to='skills.Skill'),
        ),
    ]
