# Generated by Django 3.1.13 on 2021-11-12 18:47

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        ('engineers', '0002_engineeraddon_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineeraddon',
            name='skills',
            field=mptt.fields.TreeManyToManyField(related_name='engineers', to='skills.Skill'),
        ),
    ]
