# Generated by Django 3.1.13 on 2021-11-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_auto_20211112_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatars'),
        ),
    ]
