# Generated by Django 3.1.13 on 2021-11-23 17:00

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20211112_2047'),
        ('engineers', '0005_engineerprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='engineerprofile',
            name='skills',
            field=mptt.fields.TreeManyToManyField(null=True, related_name='engineers', to='skills.Skill'),
        ),
    ]
