# Generated by Django 3.1.13 on 2021-11-23 17:02

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20211112_2047'),
        ('engineers', '0006_auto_20211123_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerprofile',
            name='skills',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='engineers', to='skills.Skill'),
        ),
    ]
