# Generated by Django 3.1.13 on 2021-11-29 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0008_auto_20211128_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerprofile',
            name='avatar',
        ),
    ]
