# Generated by Django 3.1.13 on 2022-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0009_remove_engineerprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('WEEKS', 'Weeks to months'), ('DAYS', 'Days to weeks '), ('INCIDENTAL', 'Incidental advice')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='engineerprofile',
            name='orcid_id',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
