# Generated by Django 3.1.13 on 2021-11-12 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientAddon',
            new_name='ClientProfile',
        ),
    ]
