# Generated by Django 3.1.13 on 2021-11-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ENGINEER', 'Engineer'), ('PROJECT_OWNER', 'Project Owner')], default='PROJECT_OWNER', max_length=50, verbose_name='Type'),
        ),
    ]
