# Generated by Django 3.1.13 on 2021-12-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('last_name', 'first_name')},
        ),
    ]
