# Generated by Django 3.1.13 on 2022-01-28 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0004_auto_20211207_1724'),
        ('users', '0010_auto_20211207_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='_user_favorites_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_responded', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('response', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('NO_RESPONSE', 'No Response')], default='NO_RESPONSE', max_length=20)),
                ('engineer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engineer_engagements', to=settings.AUTH_USER_MODEL)),
                ('project_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_owner_engagements', to=settings.AUTH_USER_MODEL)),
                ('projects', models.ManyToManyField(blank=True, related_name='engagements', to='project_owners.Project')),
            ],
        ),
    ]
