# Generated by Django 3.1.13 on 2022-02-01 18:52

from django.db import migrations, models
import skills_matcher_db.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220128_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=skills_matcher_db.users.models.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('EXPERT', 'Expert'), ('ENGINEER', 'Engineer'), ('PROJECT_OWNER', 'Project Owner')], max_length=50), blank=True, null=True, size=None),
        ),
    ]
