# Generated by Django 3.1.13 on 2022-02-01 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20220201_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='engineer',
            new_name='expert',
        ),
        migrations.RemoveField(
            model_name='engagement',
            name='engineer',
        ),
        migrations.AddField(
            model_name='engagement',
            name='expert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_engagements', to=settings.AUTH_USER_MODEL),
        ),
    ]
