# Generated by Django 3.1.13 on 2022-03-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220201_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagement',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
