# Generated by Django 3.1.13 on 2022-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20220317_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
