# Generated by Django 3.1.13 on 2022-04-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_engagement_engagement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
