# Generated by Django 3.1.13 on 2022-02-01 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_auto_20220201_1852'),
        ('skills', '0002_auto_20211112_2047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='ExpertProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, choices=[('WEEKS', 'Weeks to months'), ('DAYS', 'Days to weeks '), ('INCIDENTAL', 'Incidental advice')], max_length=20, null=True)),
                ('orcid_id', models.URLField(blank=True, max_length=100, null=True)),
                ('skills', mptt.fields.TreeManyToManyField(blank=True, related_name='experts', to='skills.Skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
