# Generated by Django 3.1.13 on 2022-03-23 18:40

from django.db import migrations, models
import skills_matcher_db.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20220203_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='availability',
            field=skills_matcher_db.utils.fields.ChoiceArrayField(base_field=models.CharField(blank=True, choices=[('WEEKS', 'Weeks to months'), ('DAYS', 'Days to weeks'), ('INCIDENTAL', 'Incidental advice')], max_length=25), blank=True, null=True, size=None),
        ),
    ]
