# Generated by Django 3.1.13 on 2025-04-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0003_auto_20220323_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='international_travel',
            field=models.BooleanField(default=False),
        ),
    ]
