# Generated by Django 3.1.13 on 2025-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0004_expertprofile_international_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='international_travel',
            field=models.BooleanField(default=False, verbose_name='Willing to Travel Internationally'),
        ),
    ]
