# Generated by Django 3.1.13 on 2025-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0005_auto_20250416_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='urgent_project_seek',
            field=models.BooleanField(default=False, verbose_name='Urgently Seeking New Project'),
        ),
    ]
