# Generated by Django 3.1.13 on 2026-06-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0006_expertprofile_urgent_project_seek'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='looking_for_field_work',
            field=models.BooleanField(default=False, verbose_name='Looking for Field Work'),
        ),
    ]
