# Generated by Django 3.1.13 on 2026-06-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0007_expertprofile_looking_for_field_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='available_for_seagoing',
            field=models.BooleanField(default=False, verbose_name='Available for seagoing opportunities'),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='looking_for_part_time_work',
            field=models.BooleanField(default=False, verbose_name='Looking for part-time or short-term work'),
        ),
    ]
