# Generated by Django 3.1.13 on 2021-11-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20211128_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
    ]
