# Generated by Django 3.1.13 on 2021-11-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectowner',
            options={'verbose_name': 'Project Owner'},
        ),
    ]
