# Generated by Django 3.1.13 on 2021-12-07 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_owners', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='engineers',
            field=models.ManyToManyField(blank=True, related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
