# Generated by Django 3.1.13 on 2022-02-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0004_auto_20211207_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='engineers',
            new_name='experts',
        ),
    ]
