# Generated by Django 3.1.13 on 2022-03-28 13:36

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20211112_2047'),
        ('project_owners', '0005_auto_20220201_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='projects', to='skills.Skill'),
        ),
    ]
