# Generated by Django 3.1.13 on 2022-04-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0006_project_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
    ]
