# Generated by Django 3.1.13 on 2025-04-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0007_auto_20220401_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='international_travel',
            field=models.BooleanField(default=False, verbose_name='International Travel Required'),
        ),
    ]
