# Generated by Django 3.1.13 on 2026-06-18 18:56

from django.db import migrations, models
import skills_matcher_db.project_owners.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0009_project_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reply_by_date',
            field=models.DateTimeField(default=skills_matcher_db.project_owners.models.six_months_from_now),
        ),
    ]
