# Generated by Django 3.1.13 on 2026-06-22 17:47

from django.db import migrations, models
import skills_matcher_db.project_owners.models


class Migration(migrations.Migration):

    dependencies = [
        ('project_owners', '0010_project_reply_by_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reply_by_date',
            field=models.DateField(default=skills_matcher_db.project_owners.models.six_months_from_now),
        ),
    ]
