# Generated by Django 3.1.13 on 2021-11-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('ENGINEER', 'Engineer')], default='CLIENT', max_length=50, verbose_name='Type'),
        ),
    ]
